const { contextBridge, ipcRenderer, webUtils } = require("electron");

contextBridge.exposeInMainWorld("parserApp", {
  parseFile:  (payload) => ipcRenderer.invoke("parser:parse-file", payload),
  resolvePath: (payload) => ipcRenderer.invoke("parser:resolve-path", payload),
  saveAssignment: (payload) => ipcRenderer.invoke("parser:save-assignment", payload),
  saveRejection: (payload) => ipcRenderer.invoke("parser:save-rejection", payload),
  getLearningSummary: () => ipcRenderer.invoke("parser:learning-summary"),
  resetFieldLearning: (payload) => ipcRenderer.invoke("parser:reset-field-learning", payload || {}),
  teach: (payload) => ipcRenderer.invoke("parser:teach", payload),
  getWorkspaceState: (payload) => ipcRenderer.invoke("workspace:get-state", payload || {}),
  addFilesToInbox: (payload) => ipcRenderer.invoke("workspace:add-to-inbox", payload || {}),
  openInboxItem: (payload) => ipcRenderer.invoke("workspace:open-inbox-item", payload || {}),
  openAttachment: (payload) => ipcRenderer.invoke("workspace:open-attachment", payload || {}),
  hideInboxItem: (payload) => ipcRenderer.invoke("workspace:hide-inbox-item", payload || {}),
  hideInboxWorkspaceOnly: (payload) => ipcRenderer.invoke("workspace:hide-inbox-workspace-only", payload || {}),
  markInboxOrder: (payload) => ipcRenderer.invoke("workspace:mark-inbox-order", payload || {}),
  markInboxNotOrder: (payload) => ipcRenderer.invoke("workspace:mark-inbox-not-order", payload || {}),
  undoInboxOrderMark: (payload) => ipcRenderer.invoke("workspace:undo-inbox-order-mark", payload || {}),
  setInboxLinkedOrder: (payload) => ipcRenderer.invoke("workspace:set-inbox-linked-order", payload || {}),
  openFolder:       (folderPath)  => ipcRenderer.invoke("shell:open-folder", folderPath),
  pickFile:         (opts)        => ipcRenderer.invoke("dialog:pick-file", opts || {}),
  pickFolder:       ()            => ipcRenderer.invoke("dialog:pick-folder"),
  listAttachments:  (payload)     => ipcRenderer.invoke("email:list-attachments", payload),
  getEmailEnvironment: ()         => ipcRenderer.invoke("email:get-environment"),
  resolveAttachments: (payload)   => ipcRenderer.invoke("email:resolve-attachments", payload || {}),
  composeEmail:     (payload)     => ipcRenderer.invoke("email:compose", payload),
  testSmtpConnection: (payload)   => ipcRenderer.invoke("email:test-smtp", payload || {}),
  sendDockEmail:    (payload)     => ipcRenderer.invoke("email:send-smtp", payload || {}),
  getFilePath:       (file)       => webUtils.getPathForFile(file),
  setTitle:            (title)   => ipcRenderer.invoke("app:set-title", title),
  exportPrintPdf:      (payload) => ipcRenderer.invoke("orders:export-print-pdf", payload),
  generateGiftLetter:  (payload) => ipcRenderer.invoke("documents:generate-gift-letter", payload),
  saveJson:            (payload) => ipcRenderer.invoke("file:save-json", payload),
  backupSave:          (payload) => ipcRenderer.invoke("backup:save", payload),
  backupRestore:       (payload) => ipcRenderer.invoke("backup:restore", payload),
  openFile:            (payload) => ipcRenderer.invoke("documents:open-file", payload),
});

contextBridge.exposeInMainWorld("electronAPI", {
  openExternal: (url) => ipcRenderer.invoke("open-external", url),
});
