export const ORDER_FIELD_STORAGE = Object.freeze({
  orders: "orders",
  items: "items",
  derived: "derived",
});

export const ORDER_FIELD_MANAGEMENT = Object.freeze({
  parser: "parser",
  manual: "manual",
  both: "both",
});

export const OPERATIONAL_ORDER_FIELDS = Object.freeze([
  {
    key: "buyer_name",
    label: "Buyer",
    storage: ORDER_FIELD_STORAGE.orders,
    storageKey: "buyer_name",
    desktopOrder: 1,
    webOrder: 1,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "shipping_name",
    label: "Shipping name",
    storage: ORDER_FIELD_STORAGE.orders,
    storageKey: "shipping_name",
    desktopOrder: 2,
    webOrder: 2,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "buyer_email",
    label: "Buyer email",
    storage: ORDER_FIELD_STORAGE.orders,
    storageKey: "buyer_email",
    desktopOrder: 3,
    webOrder: 3,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["email"],
    persisted: true,
  },
  {
    key: "shipping_address",
    label: "Shipping address",
    storage: ORDER_FIELD_STORAGE.orders,
    storageKey: "shipping_address",
    desktopOrder: 4,
    webOrder: 4,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
    multiline: true,
  },
  {
    key: "phone_number",
    label: "Phone",
    storage: ORDER_FIELD_STORAGE.orders,
    storageKey: "phone_number",
    desktopOrder: 5,
    webOrder: 5,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "order_number",
    label: "Order number",
    storage: ORDER_FIELD_STORAGE.orders,
    storageKey: "order_number",
    desktopOrder: 6,
    webOrder: 6,
    required: true,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "order_date",
    label: "Order date",
    storage: ORDER_FIELD_STORAGE.orders,
    storageKey: "order_date",
    desktopOrder: 7,
    webOrder: 7,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "ship_by",
    label: "Ship by",
    storage: ORDER_FIELD_STORAGE.orders,
    storageKey: "ship_by",
    desktopOrder: 8,
    webOrder: 8,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "price",
    label: "Price",
    storage: ORDER_FIELD_STORAGE.items,
    storageKey: "price",
    desktopOrder: 9,
    webOrder: 9,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "quantity",
    label: "Quantity",
    storage: ORDER_FIELD_STORAGE.items,
    storageKey: "quantity",
    desktopOrder: 10,
    webOrder: 10,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
    inputType: "number",
  },
  {
    key: "pet_name",
    label: "Pet name",
    storage: ORDER_FIELD_STORAGE.items,
    storageKey: "custom_1",
    desktopOrder: 11,
    webOrder: 11,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "pet_type",
    label: "Pet type",
    storage: ORDER_FIELD_STORAGE.items,
    storageKey: "custom_2",
    desktopOrder: 12,
    webOrder: 12,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "epitaph",
    label: "Epitaph",
    storage: ORDER_FIELD_STORAGE.items,
    storageKey: "custom_3",
    desktopOrder: 13,
    webOrder: 13,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "dates_of_life",
    label: "Dates of life",
    storage: ORDER_FIELD_STORAGE.items,
    storageKey: "custom_4",
    desktopOrder: 14,
    webOrder: 14,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "stone_color",
    label: "Stone color",
    storage: ORDER_FIELD_STORAGE.items,
    storageKey: "custom_5",
    desktopOrder: 15,
    webOrder: 15,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card"],
    persisted: true,
  },
  {
    key: "stone_type",
    label: "Stone type",
    storage: ORDER_FIELD_STORAGE.items,
    storageKey: "custom_6",
    desktopOrder: 16,
    webOrder: 16,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card"],
    persisted: true,
  },
  {
    key: "order_notes",
    label: "Notes",
    storage: ORDER_FIELD_STORAGE.items,
    storageKey: "order_notes",
    desktopOrder: 18,
    webOrder: 18,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "email"],
    persisted: true,
    multiline: true,
  },
  {
    key: "gift_message",
    label: "Gift message",
    storage: ORDER_FIELD_STORAGE.items,
    storageKey: "gift_message",
    desktopOrder: 19,
    webOrder: 19,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["gift", "email"],
    persisted: true,
    multiline: true,
  },
]);

export const OPERATIONAL_ORDER_FIELD_KEYS = Object.freeze(
  OPERATIONAL_ORDER_FIELDS.map((field) => field.key)
);

export const OPERATIONAL_ORDER_FIELD_BY_KEY = Object.freeze(
  Object.fromEntries(OPERATIONAL_ORDER_FIELDS.map((field) => [field.key, field]))
);

export function orderFieldsByStorage(storage) {
  return OPERATIONAL_ORDER_FIELDS.filter((field) => field.storage === storage);
}

