export const ORDER_FIELD_STORAGE = Object.freeze({
  orders: "orders",
  items: "items",
  derived: "derived",
});

export const ORDER_FIELD_MANAGEMENT = Object.freeze({
  parser: "parser",
  manual: "manual",
  both: "both",
});

export const OPERATIONAL_ORDER_FIELDS = Object.freeze([
  {
    key: "order_number",
    label: "Order Number",
    storage: ORDER_FIELD_STORAGE.orders,
    storageKey: "order_number",
    desktopOrder: 1,
    webOrder: 1,
    required: true,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "order_date",
    label: "Order Date",
    storage: ORDER_FIELD_STORAGE.orders,
    storageKey: "order_date",
    desktopOrder: 2,
    webOrder: 2,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "ship_by",
    label: "Ship By",
    storage: ORDER_FIELD_STORAGE.orders,
    storageKey: "ship_by",
    desktopOrder: 3,
    webOrder: 3,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "billing_name",
    label: "Billing Name",
    storage: ORDER_FIELD_STORAGE.orders,
    storageKey: "billing_name",
    desktopOrder: 4,
    webOrder: 4,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "billing_address",
    label: "Billing Address",
    storage: ORDER_FIELD_STORAGE.orders,
    storageKey: "billing_address",
    desktopOrder: 5,
    webOrder: 5,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["card", "email"],
    persisted: true,
    multiline: true,
  },
  {
    key: "billing_email",
    label: "Email",
    storage: ORDER_FIELD_STORAGE.orders,
    storageKey: "billing_email",
    desktopOrder: 6,
    webOrder: 6,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["email"],
    persisted: true,
  },
  {
    key: "phone_number",
    label: "Phone Number",
    storage: ORDER_FIELD_STORAGE.orders,
    storageKey: "phone_number",
    desktopOrder: 7,
    webOrder: 7,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "recipient_name",
    label: "Shipping Name",
    storage: ORDER_FIELD_STORAGE.orders,
    storageKey: "recipient_name",
    desktopOrder: 8,
    webOrder: 8,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "shipping_address",
    label: "Shipping Address",
    storage: ORDER_FIELD_STORAGE.orders,
    storageKey: "shipping_address",
    desktopOrder: 9,
    webOrder: 9,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
    multiline: true,
  },
  {
    key: "quantity",
    label: "Quantity",
    storage: ORDER_FIELD_STORAGE.items,
    storageKey: "quantity",
    desktopOrder: 10,
    webOrder: 10,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
    inputType: "number",
  },
  {
    key: "price",
    label: "Price",
    storage: ORDER_FIELD_STORAGE.items,
    storageKey: "price",
    desktopOrder: 11,
    webOrder: 11,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "pet_name",
    label: "Pet name",
    storage: ORDER_FIELD_STORAGE.items,
    storageKey: "custom_1",
    desktopOrder: 12,
    webOrder: 12,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "pet_type",
    label: "Pet type",
    storage: ORDER_FIELD_STORAGE.items,
    storageKey: "custom_2",
    desktopOrder: 12,
    webOrder: 12,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "epitaph",
    label: "Epitaph",
    storage: ORDER_FIELD_STORAGE.items,
    storageKey: "custom_3",
    desktopOrder: 13,
    webOrder: 13,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "dates_of_life",
    label: "Dates of life",
    storage: ORDER_FIELD_STORAGE.items,
    storageKey: "custom_4",
    desktopOrder: 14,
    webOrder: 14,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card", "email"],
    persisted: true,
  },
  {
    key: "stone_color",
    label: "Stone color",
    storage: ORDER_FIELD_STORAGE.items,
    storageKey: "custom_5",
    desktopOrder: 15,
    webOrder: 15,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card"],
    persisted: true,
  },
  {
    key: "stone_type",
    label: "Stone type",
    storage: ORDER_FIELD_STORAGE.items,
    storageKey: "custom_6",
    desktopOrder: 16,
    webOrder: 16,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "card"],
    persisted: true,
  },
  {
    key: "order_notes",
    label: "Notes",
    storage: ORDER_FIELD_STORAGE.items,
    storageKey: "order_notes",
    desktopOrder: 18,
    webOrder: 18,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["sheet", "email"],
    persisted: true,
    multiline: true,
  },
  {
    key: "gift_message",
    label: "Gift message",
    storage: ORDER_FIELD_STORAGE.items,
    storageKey: "gift_message",
    desktopOrder: 19,
    webOrder: 19,
    required: false,
    managedBy: ORDER_FIELD_MANAGEMENT.both,
    printRelevance: ["gift", "email"],
    persisted: true,
    multiline: true,
  },
]);

export const OPERATIONAL_ORDER_FIELD_KEYS = Object.freeze(
  OPERATIONAL_ORDER_FIELDS.map((field) => field.key)
);

export const OPERATIONAL_ORDER_FIELD_BY_KEY = Object.freeze(
  Object.fromEntries(OPERATIONAL_ORDER_FIELDS.map((field) => [field.key, field]))
);

export const HIDDEN_LEGACY_ORDER_FIELD_KEYS = Object.freeze([
  "buyer_name",
  "buyer_email",
  "shipping_name",
]);

export const OPERATIONAL_ORDER_FIELD_SECTIONS = Object.freeze([
  {
    id: "order_core",
    label: "Order Core",
    keys: Object.freeze(["order_number", "order_date", "ship_by"]),
  },
  {
    id: "billing",
    label: "Billing / Purchaser",
    keys: Object.freeze(["billing_name", "billing_address", "billing_email", "phone_number"]),
  },
  {
    id: "shipping",
    label: "Shipping / Recipient",
    keys: Object.freeze(["recipient_name", "shipping_address"]),
  },
  {
    id: "gift",
    label: "Gift",
    keys: Object.freeze(["is_gift", "gift_wrap", "gift_message"]),
  },
  {
    id: "remaining",
    label: "Remaining Order Details",
    keys: Object.freeze([
      "quantity",
      "price",
      "pet_name",
      "pet_type",
      "epitaph",
      "dates_of_life",
      "stone_color",
      "stone_type",
      "order_notes",
    ]),
  },
]);

export function orderFieldsByStorage(storage) {
  return OPERATIONAL_ORDER_FIELDS.filter((field) => field.storage === storage);
}

