export const API_ENDPOINTS = Object.freeze({
  health: "/health",
  account: "/account/profile",
  accountLogo: "/account/logo",
  accountCapabilities: "/account/capabilities",
  accountSession: "/account/session",
  accountEntitlements: "/account/entitlements",
  authSignup: "/account/auth/signup",
  authLogin: "/account/auth/login",
  authLogout: "/account/auth/logout",
  passwordResetRequest: "/account/auth/password-reset/request",
  passwordResetConfirm: "/account/auth/password-reset/confirm",
  trialStart: "/account/subscription/trial/start",
  subscription: "/account/subscription",
  billingCheckout: "/account/billing/checkout",
  billingPortal: "/account/billing/portal",
  documentsConfig: "/account/documents-config",
  documentAsset: (assetKey) => `/account/document-assets/${encodeURIComponent(assetKey)}`,
  documentAssetFile: (assetKey) => `/account/document-assets/${encodeURIComponent(assetKey)}/file`,
  thankYouTemplate: "/account/thank-you-template",
  thankYouTemplateFile: "/account/thank-you-template/file",
  orderFieldLayout: "/account/order-field-layout",
  dateConfig: "/account/date-config",
  pricingRules: "/account/pricing-rules",
  printConfig: "/account/print-config",
  webSettings: "/account/web-settings",
  ordersList: "/orders/list",
  orderDetail: (orderId) => `/orders/${encodeURIComponent(orderId)}`,
  orderUpdate: (orderId) => `/orders/${encodeURIComponent(orderId)}`,
  orderUpdateFull: "/orders/update-full",
  orderMessages: (orderId) => `/orders/${encodeURIComponent(orderId)}/messages`,
  orderAttachments: (orderId) => `/orders/${encodeURIComponent(orderId)}/attachments`,
  itemStatus: (itemId) => `/items/${encodeURIComponent(itemId)}/status`,
  archiveSearch: "/orders/archive/search",
  inboxEvents: "/inbox/events",
});

export const DEFAULT_LOCAL_API_BASE = "http://127.0.0.1:8055";
